version: '3'
# name: inception

services:
  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception_net
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_net
    volumes:
      - wp_data:/var/www/html/wp-content
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    networks:
      - inception_net
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wp
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/db

networks:
  inception_net: {}
