version: '3'
# name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    expose:
      - 9000
    networks:
      - inception_net
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - 9000
      - 3306
    networks:
      - inception_net
    volumes:
      - wp_data:/var/www/html
    environment:
      - WPDB_HOST=mariadb
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - 3306
    networks:
      - inception_net
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wp
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/db

networks:
  inception_net:
    name: inception_net
