FROM debian:bullseye

RUN apt-get update && apt-get install -y \
	wget \
	php7.4 \
	php7.4-fpm \
	php7.4-mysqli \
	php7.4-gd \
	php7.4-curl \
	php7.4-mbstring \
	mariadb-client

# php7.4-xml  php7.4-zip

